# Generated by Django 5.2.4 on 2025-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
