# Generated by Django 5.1.3 on 2025-08-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('roll', models.PositiveBigIntegerField(null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('images', models.ImageField(null=True, upload_to='media/images')),
            ],
        ),
    ]
