# Generated by Django 5.2.4 on 2025-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='roll',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
