# Generated by Django 5.2.1 on 2025-07-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_alter_studentprofilemodel_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
