# Generated by Django 5.2.4 on 2025-07-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_phone', models.CharField(max_length=15, null=True)),
                ('student_profile', models.ImageField(null=True, upload_to='Media/Profile/Students')),
            ],
        ),
    ]
