# Generated by Django 5.2.5 on 2025-08-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_customusermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/profile'),
        ),
    ]
