# Generated by Django 5.2.3 on 2025-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('phohe', models.CharField(max_length=17)),
            ],
        ),
    ]
