# Generated by Django 5.2.3 on 2025-06-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/recipe'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='instructions',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
