# Generated by Django 5.2.4 on 2025-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobNestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
