# Generated by Django 5.2.4 on 2025-07-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_candidateprofilemodel_email_and_more'),
        ('employer_app', '0004_alter_jobmodel_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_application', to='candidate_app.candidateprofilemodel'),
        ),
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='employer_app.jobmodel'),
        ),
    ]
