# Generated by Django 5.2.4 on 2025-07-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0003_alter_employerprofilemodel_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_job', to='employer_app.employerprofilemodel'),
        ),
    ]
