# Generated by Django 5.2.5 on 2025-08-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('deadline', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
