# Generated by Django 5.2.5 on 2025-08-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0003_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('department', models.PositiveIntegerField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Staff', 'Staff')], null=True)),
            ],
        ),
    ]
