# Generated by Django 5.2.5 on 2025-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0004_employeemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Staff', 'Staff')], null=True),
        ),
    ]
