# Generated by Django 5.1.3 on 2025-06-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
