# Generated by Django 5.2.4 on 2025-07-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfoForm',
            new_name='UserInfoModel',
        ),
    ]
