# Generated by Django 5.2.4 on 2025-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_rename_userinfoform_userinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='media/profile')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
