# Generated by Django 5.2.3 on 2025-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_customusermodel_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
