# Generated by Django 5.2.4 on 2025-07-26 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_management_app', '0002_departmentmodel_employeemanagementmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual_leave', 'Casual_leave'), ('Sick_leave', 'Sick_leave'), ('Annual_leave', 'Annual_leave'), ('Paternity_leave', 'Paternity_leave')], max_length=100, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('resason', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_info', to='office_management_app.employeemanagementmodel')),
            ],
        ),
    ]
