# Generated by Django 5.2.4 on 2025-07-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_management_app', '0003_leavemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemodel',
            old_name='resason',
            new_name='reason',
        ),
    ]
