# Generated by Django 5.2.4 on 2025-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthApp', '0002_pendingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pendingmodel',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
