# Generated by Django 5.2.3 on 2025-06-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'InProgress'), ('completed', 'Completed')], max_length=100, null=True),
        ),
    ]
